pipeline {
  agent any 
  tools {
    nodejs "node25"
  }
  environment {
    SONAR_HOME = tool "sonar"
  }
  stages {
    stage("Checkout") {
      steps{
        git branch: "ci/jenkins", url: "https://github.com/AmulThantharate/zenith.git"
      }
    }
    stage("Imaeg Tag") {
      steps{
        script{
          env.IMAGE_TAG = sh(script: 'git log -1 --format="%h"', returnStdout: true).trim()
        }
      }
    }
    stage('Install Dependencies & Test') {
            parallel {
                stage('Install Dependencies') {
                    steps {
                        dir('backend') {
                            sh '''
                                echo "=== Installing Dependencies ==="
                                npm ci --prefer-offline --no-audit
                            '''
                        }
                    }
                }
                stage('Lint') {
                    steps {
                        dir('backend') {
                            sh '''
                                echo "=== Running Linter ==="
                                npm run lint || true
                            '''
                        }
                    }
                }
          }
    }
    stage('SonarQube Analysis') {
      steps {
          dir('backend') {
              withSonarQubeEnv('sonar') {
                  sh """
                      echo "=== Running SonarQube Analysis ==="
                      npx sonar-scanner \
                                -Dsonar.projectName='Backend Service' \
                                -Dsonar.sources=. \
                                -Dsonar.tests=. \
                                -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js \
                                -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
                                -Dsonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**
                        """
                    }
                }
            }
        }
        stage("Quality Gate"){
            steps{
                timeout(time: 5, unit:"MINUTES"){
                    waitForQualityGate abortPipeline: true
                }
            }
        }
  }
}